spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/crm-web
    password:
    username:
    driverClassName: org.postgresql.Driver
